version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/express_app

hooks:
  ApplicationStop:
    - location: scripts/stop_app.sh
      timeout: 300
  BeforeInstall:
    - location: scripts/pre_install_app.sh
      timeout: 30
  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 300

