version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/express_app

hooks:
  BeforeInstall:
    - location: scripts/pre_install_app.sh
      timeout: 30
      runas: root
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 300
  ApplicationStop:
    - location: scripts/stop_app.sh
      timeout: 300
  # ValidateService:
  #   - location: scripts/monitor_app.sh
  #     timeout: 300
  #     runas: root
