version: 0.0
os: Ubuntu
files:
  - source: /
    destination: /home/ubuntu/express-app
    file_exists_behavior: OVERWRITE

hooks:
  # ApplicationStop:
  #   - location: scripts/app_stop
  #     timeout: 300
  # BeforeInstall:
  #   - location: scripts/app_stop
  #     timeout: 300
  Install:
    - location: scripts/install_dependencies
      timeout: 3600
  ApplicationStart:
    - location: scripts/app_start
      timeout: 300
  ValidateService:
    - location: scripts/app_monitor
      timeout: 3600
      runas: root
